### ISSUE TITLE
Must pass a username and/or OAuth options when creating an AuthInfo instance.

### ISSUE THREAD

**Issue by ChuckJonas** [lodossDev/sfdx-login#1]
Ran the command and it looks like it successfully logged me in but failed in setting up the sdfx org.
```
{11:09}~➭ sfdx force:auth:default:login -s https://login.salesforce.com  -u ell****** -p *********
Logged in as: ell**** (005**********)
Organization: Sp**** (00D***********)
ERROR running DefaultLogin:  Must pass a username and/or OAuth options when creating an AuthInfo instance.
```

When I run `sfdx force:org:list`, I do not see the user in the returned results.

**Comment by lodossDev** [comment]
@ChuckJonas thanks for this, not sure why this happened as it worked before on v44, must be because of the new sfdx version v45.
